### ISSUE TITLE
Err: unable to parse status

### ISSUE THREAD

**Issue by tcondit** [tanin47/git-notes#10]
I'm curious what's causing this error. It's not a blocking issue--these changes and a couple others were successfully committed to my local repo. It reproduces consistently, with every detected change.

* It's interesting to me that the starting state is `error`.
* Changes were indeed committed, but they were **not** pushed.
* This is a work machine, so I obscured the hostname (`LAPTOP-HOSTNAME`).

```
❯ ./git-notes git-notes.json
2020/06/11 15:07:02 Git Notes is starting...
&{[/Users/tcondit/Bender/3_Resources/vimwiki/]}
2020/06/11 15:07:02 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
2020/06/11 15:07:03 Starting state: error
2020/06/11 15:07:03 Syncing failed. Err: performing GetState() failed. Err: unable to parse status: ## LAPTOP-HOSTNAME...origin/LAPTOP-HOSTNAME
2020/06/11 15:07:03 Git notes is monitoring /Users/tcondit/Bender/3_Resources/vimwiki/
2020/06/11 15:08:03 Changes have been detected.
2020/06/11 15:08:05 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
2020/06/11 15:08:05 Starting state: dirty
2020/06/11 15:08:05 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
[LAPTOP-HOSTNAME df32c77] Commited at 2020-06-11 15:08:05.408897 -0700 PDT m=+63.172554816
 2 files changed, 2 insertions(+)
 create mode 100644 testing-git-notes.md
2020/06/11 15:08:05 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
2020/06/11 15:08:06 Syncing failed. Err: performing GetState() failed. Err: unable to parse status: ## LAPTOP-HOSTNAME...origin/LAPTOP-HOSTNAME [ahead 1]
2020/06/11 15:11:20 Changes have been detected.
2020/06/11 15:11:22 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
2020/06/11 15:11:22 Starting state: dirty
2020/06/11 15:11:22 Computing the state of /Users/tcondit/Bender/3_Resources/vimwiki/
[LAPTOP-HOSTNAME 503a2fb] Commited at 2020-06-11 15:11:22.751097 -0700 PDT m=+260.511405293
 1 file changed, 4 insertions(+)
```

**Comment by tanin47** [comment]
Apparently, this regex only parse the master branch: https://github.com/tanin47/git-notes/blob/f1ef341555faad982a594240b46409ffa37260bb/git.go#L107

If you cannot use the master branch, I'll fix it. Please let me know.

If you could share your context a bit as to why you aren't using `master`, I'd love to learn about it.

**Comment by tcondit** [comment]
Ah, I didn't see that regex.

My use case: I've got personal and work machines, and have been experimenting with maintaining notes for each in separate branches. But it seems like the cost outweighs the benefit. I'm going to switch both to `master`.

**Comment by tanin47** [comment]
I also use this for both work and personal machine.

But I actually separate the repos. The work one goes to internal git, and the personal one goes to GitHub.com.

Thank you for sharing your setting. I'll close the issue.
