### ISSUE TITLE
Binary not created with current build instructions on macOS

### ISSUE THREAD

**Issue by Bargsteen** [tanin47/git-notes#13]
Hi, I just attempted to install git-notes on a new machine, but I ran into a minor issue with the install instructions, which meant that it didn't produce the `git-notes` binary.

And thanks for the otherwise flawless tool ;) 

## Steps
1. Run `go build *.go` inside the root of the repo

## Expected
The `git-notes` binary is built.

## Actual
The binary isn't built. (No output is given by the command).

## Workaround
When I ran `go build` (without `*.go`) it suggested that I initialize the module with `go mod init`.
After initializing the module, the binary was produced by running `go build`.

So, at least for macOS, the build instructions should be `go mod init; go build`  😊 

## Setup
- OS: macOS 11.6.5
- Go: 1.18.4

**Comment by psydvl** [comment]
I think, better to use `go install github.com/tanin47/git-notes`, rather then actual install instruction

**Comment by tanin47** [comment]
Thank you for the recommendation. The new version of go changes the build command.

I'll change the readme to: `go mod init; go build`.

`go install github.com/tanin47/git-notes` is good too. but I haven't tried.
