### ISSUE TITLE
Add some license

### ISSUE THREAD

**Issue by TeddyDD** [tanin47/git-notes#5]
Could you add explicit license to repository (for example in LICENSE file or in the README?)

Without explicit license this project is „All right Reserved”, even if
that's your intent it would be better to state that explicitly.

**Comment by tanin47** [comment]
@TeddyDD Thank you for raising this concern. I've added the MIT license. Please let me know if this license doesn't work for you.

**Comment by TeddyDD** [comment]
Thank you :)
